language: java

dist: trusty

addons:
  sonarcloud:
    organization: "luizaraujojr"
    token:
      secure: ad3e05938f11cff17e468421902acdaa12c2e0cb # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner